import type { task } from "@schemas/task";

export const mockTasks: task.task[] = [
  {
    id: 1,
    title: "Task 1: Plan Documentation",
    description:
      "Optimize database queries for better performance. High impact.",
    dueAt: { date: "2026-05-21", time: "00:00" },
    priority: "High",
    status: "done",
    tags: ["Design", "Work", "Personal", "Meeting"],
    assignee: "Heidi",
    createdAt: { date: "2026-05-06", time: "02:30" },
    updatedAt: { date: "2026-05-15", time: "02:45" },
  },
  {
    id: 2,
    title: "Task 2: Test Database",
    description: "Prepare quarterly report. Coordinate with team.",
    dueAt: { date: "2026-03-07", time: "10:15" },
    priority: "Low",
    status: "in-progress",
    tags: ["Meeting"],
    assignee: "Heidi",
    createdAt: { date: "2026-02-07", time: "12:45" },
    updatedAt: { date: "2026-02-28", time: "11:45" },
  },
  {
    id: 3,
    title: "Task 3: Implement Feature",
    description:
      "Update the documentation for the latest release. Coordinate with team.",
    dueAt: { date: "2026-01-02", time: "01:30" },
    priority: "Low",
    status: "review",
    tags: ["Research"],
    assignee: "Eve",
    createdAt: { date: "2025-12-07", time: "17:15" },
    updatedAt: { date: "2025-12-30", time: "17:15" },
  },
  {
    id: 4,
    title: "Task 4: Deploy Feature",
    description: "Design the new dashboard layout. High impact.",
    dueAt: { date: "2026-02-11", time: "22:30" },
    priority: "High",
    status: "in-progress",
    tags: ["Planning", "Personal", "Research"],
    assignee: "Judy",
    createdAt: { date: "2026-01-21", time: "22:45" },
    updatedAt: { date: "2026-01-21", time: "00:15" },
  },
  {
    id: 5,
    title: "Task 5: Research API",
    description: "Prepare quarterly report. High impact.",
    dueAt: { date: "2026-03-10", time: "10:00" },
    priority: "Low",
    status: "in-progress",
    tags: ["Planning", "Work", "Review", "Bug"],
    assignee: "Grace",
    createdAt: { date: "2026-02-22", time: "15:15" },
    updatedAt: { date: "2026-02-27", time: "14:15" },
  },
  {
    id: 6,
    title: "Task 6: Fix Presentation",
    description:
      "Write unit tests for the payment module. Coordinate with team.",
    dueAt: { date: "2026-04-18", time: "15:15" },
    priority: "Low",
    status: "done",
    tags: ["Meeting", "Feature"],
    assignee: "Charlie",
    createdAt: { date: "2026-04-07", time: "23:15" },
    updatedAt: { date: "2026-04-10", time: "03:45" },
  },
  {
    id: 7,
    title: "Task 7: Test Bug",
    description: "Resolve the login issue reported by users. ASAP",
    dueAt: { date: "2026-01-16", time: "17:00" },
    priority: "High",
    status: "todo",
    tags: ["Planning", "Review", "Personal", "Bug"],
    assignee: "David",
    createdAt: { date: "2026-01-06", time: "20:15" },
    updatedAt: { date: "2026-01-12", time: "10:45" },
  },
  {
    id: 8,
    title: "Task 8: Test Feature",
    description: "Complete the new user onboarding flow. ASAP",
    dueAt: { date: "2026-02-17", time: "03:45" },
    priority: "Low",
    status: "in-progress",
    tags: ["Research"],
    assignee: "Bob",
    createdAt: { date: "2026-01-18", time: "13:30" },
    updatedAt: { date: "2026-02-09", time: "13:00" },
  },
  {
    id: 9,
    title: "Task 9: Test Documentation",
    description: "Design the new dashboard layout. Details in attached notes.",
    dueAt: { date: "2026-01-19", time: "15:15" },
    priority: "Medium",
    status: "done",
    tags: ["Personal"],
    assignee: "Eve",
    createdAt: { date: "2026-01-16", time: "22:00" },
    updatedAt: { date: "2026-01-19", time: "23:15" },
  },
  {
    id: 10,
    title: "Task 10: Research Bug",
    description: "Resolve the login issue reported by users. High impact.",
    dueAt: { date: "2025-12-29", time: "05:45" },
    priority: "High",
    status: "in-progress",
    tags: ["Research", "Urgent", "Work", "Meeting"],
    assignee: "Grace",
    createdAt: { date: "2025-12-05", time: "15:15" },
    updatedAt: { date: "2025-12-07", time: "12:15" },
  },
  {
    id: 11,
    title: "Task 11: Migrate Legacy System",
    description:
      "Coordinate with infrastructure team to migrate old CRM to new cloud platform. Prepare rollback plan.",
    dueAt: { date: "2026-01-15", time: "18:00" },
    priority: "High",
    status: "in-progress",
    tags: ["Infrastructure", "Migration", "Critical"],
    assignee: "Alex",
    createdAt: { date: "2025-12-10", time: "09:00" },
    updatedAt: { date: "2025-12-12", time: "14:30" },
  },
  {
    id: 12,
    title: "Task 12: Conduct Security Audit",
    description:
      "Perform quarterly penetration testing and vulnerability scan on production servers.",
    dueAt: { date: "2026-01-08", time: "17:00" },
    priority: "High",
    status: "todo",
    tags: ["Security", "Compliance", "Audit"],
    assignee: "Nina",
    createdAt: { date: "2025-12-01", time: "11:45" },
    updatedAt: { date: "2025-12-01", time: "11:45" },
  },
  {
    id: 13,
    title: "Task 13: Prepare Customer Demo",
    description:
      "Build customized demo for key client showcasing new analytics dashboard features.",
    dueAt: { date: "2025-12-20", time: "14:00" },
    priority: "High",
    status: "in-progress",
    tags: ["Sales", "Demo", "Client"],
    assignee: "Marcus",
    createdAt: { date: "2025-12-11", time: "16:20" },
    updatedAt: { date: "2025-12-12", time: "10:15" },
  },
  {
    id: 14,
    title: "Task 14: Update API Documentation",
    description:
      "Revise public API docs to reflect v2.1 changes and add new endpoint examples.",
    dueAt: { date: "2026-01-05", time: "23:59" },
    priority: "Medium",
    status: "todo",
    tags: ["Documentation", "API", "Developer"],
    assignee: "Sophie",
    createdAt: { date: "2025-12-09", time: "13:00" },
    updatedAt: { date: "2025-12-09", time: "13:00" },
  },
  {
    id: 15,
    title: "Task 15: Onboard New Team Member",
    description:
      "Set up accounts, schedule training sessions, and assign mentor for new backend engineer.",
    dueAt: { date: "2025-12-23", time: "17:00" },
    priority: "Medium",
    status: "done",
    tags: ["HR", "Onboarding", "Team"],
    assignee: "Lisa",
    createdAt: { date: "2025-12-05", time: "08:30" },
    updatedAt: { date: "2025-12-18", time: "15:45" },
  },
  {
    id: 16,
    title: "Task 16: Optimize Frontend Bundle",
    description:
      "Reduce main bundle size by 30% through code splitting and lazy loading.",
    dueAt: { date: "2026-02-01", time: "12:00" },
    priority: "Medium",
    status: "in-progress",
    tags: ["Performance", "Frontend", "Optimization"],
    assignee: "Raj",
    createdAt: { date: "2025-12-08", time: "10:00" },
    updatedAt: { date: "2025-12-12", time: "18:20" },
  },
  {
    id: 17,
    title: "Task 17: Plan Q1 Roadmap",
    description:
      "Facilitate workshop with product and engineering to finalize Q1 2026 priorities.",
    dueAt: { date: "2025-12-19", time: "16:00" },
    priority: "High",
    status: "review",
    tags: ["Planning", "Roadmap", "Strategy"],
    assignee: "Emma",
    createdAt: { date: "2025-12-02", time: "14:00" },
    updatedAt: { date: "2025-12-11", time: "11:30" },
  },
  {
    id: 18,
    title: "Task 18: Fix Payment Gateway Integration",
    description:
      "Resolve intermittent failures in Stripe webhook processing during high traffic.",
    dueAt: { date: "2025-12-18", time: "23:59" },
    priority: "High",
    status: "in-progress",
    tags: ["Bug", "Payment", "Urgent"],
    assignee: "Omar",
    createdAt: { date: "2025-12-10", time: "20:45" },
    updatedAt: { date: "2025-12-12", time: "23:10" },
  },
  {
    id: 19,
    title: "Task 19: Analyze User Feedback",
    description:
      "Compile and categorize feedback from last month's NPS survey for product improvements.",
    dueAt: { date: "2026-01-10", time: "15:00" },
    priority: "Low",
    status: "todo",
    tags: ["Analytics", "UX", "Research"],
    assignee: "Clara",
    createdAt: { date: "2025-12-06", time: "09:15" },
    updatedAt: { date: "2025-12-06", time: "09:15" },
  },
  {
    id: 20,
    title: "Task 20: Schedule Team Retrospective",
    description:
      "Organize end-of-year retrospective meeting and prepare agenda and facilitation materials.",
    dueAt: { date: "2025-12-30", time: "11:00" },
    priority: "Medium",
    status: "done",
    tags: ["Team", "Retrospective", "Process"],
    assignee: "Victor",
    createdAt: { date: "2025-12-09", time: "12:00" },
    updatedAt: { date: "2025-12-16", time: "14:30" },
  },
  {
    id: 21,
    title: "Task 21: Implement Dark Mode",
    description:
      "Add full dark mode support across the web application using CSS variables and user preference detection.",
    dueAt: { date: "2026-01-20", time: "17:00" },
    priority: "Medium",
    status: "in-progress",
    tags: ["UI", "Frontend", "Feature"],
    assignee: "Elena",
    createdAt: { date: "2025-12-11", time: "10:30" },
    updatedAt: { date: "2025-12-12", time: "16:45" },
  },
  {
    id: 22,
    title: "Task 22: Set Up CI/CD Pipeline",
    description:
      "Configure GitHub Actions for automated testing, building, and deployment to staging environment.",
    dueAt: { date: "2026-01-12", time: "23:59" },
    priority: "High",
    status: "todo",
    tags: ["DevOps", "Automation", "Infrastructure"],
    assignee: "Liam",
    createdAt: { date: "2025-12-04", time: "14:00" },
    updatedAt: { date: "2025-12-04", time: "14:00" },
  },
  {
    id: 23,
    title: "Task 23: Write Integration Tests",
    description:
      "Add end-to-end tests for the new checkout flow using Cypress.",
    dueAt: { date: "2026-01-25", time: "18:00" },
    priority: "Medium",
    status: "in-progress",
    tags: ["Testing", "QA", "E2E"],
    assignee: "Zoe",
    createdAt: { date: "2025-12-10", time: "11:15" },
    updatedAt: { date: "2025-12-12", time: "15:30" },
  },
  {
    id: 24,
    title: "Task 24: Refactor Authentication Service",
    description:
      "Migrate from token-based auth to OAuth 2.0 with refresh tokens for improved security.",
    dueAt: { date: "2026-02-10", time: "12:00" },
    priority: "High",
    status: "review",
    tags: ["Backend", "Security", "Refactor"],
    assignee: "Nathan",
    createdAt: { date: "2025-12-03", time: "09:00" },
    updatedAt: { date: "2025-12-12", time: "20:00" },
  },
  {
    id: 25,
    title: "Task 25: Design Marketing Landing Page",
    description:
      "Create high-converting landing page mockups for upcoming product launch campaign.",
    dueAt: { date: "2025-12-24", time: "17:00" },
    priority: "High",
    status: "in-progress",
    tags: ["Design", "Marketing", "Campaign"],
    assignee: "Isabella",
    createdAt: { date: "2025-12-08", time: "13:45" },
    updatedAt: { date: "2025-12-12", time: "11:20" },
  },
  {
    id: 26,
    title: "Task 26: Monitor Production Metrics",
    description:
      "Set up alerts for key performance indicators and review weekly health reports.",
    dueAt: { date: "2026-01-05", time: "10:00" },
    priority: "Low",
    status: "done",
    tags: ["Monitoring", "SRE", "Operations"],
    assignee: "Diego",
    createdAt: { date: "2025-12-02", time: "15:00" },
    updatedAt: { date: "2025-12-10", time: "09:30" },
  },
  {
    id: 27,
    title: "Task 27: Prepare Budget Forecast",
    description:
      "Compile Q1 2026 department budget including headcount and tool subscriptions.",
    dueAt: { date: "2025-12-31", time: "18:00" },
    priority: "High",
    status: "todo",
    tags: ["Finance", "Planning", "Budget"],
    assignee: "Sarah",
    createdAt: { date: "2025-12-07", time: "10:00" },
    updatedAt: { date: "2025-12-07", time: "10:00" },
  },
  {
    id: 28,
    title: "Task 28: Localize Mobile App",
    description:
      "Add Spanish and French translations for all user-facing strings in the iOS and Android apps.",
    dueAt: { date: "2026-02-15", time: "23:59" },
    priority: "Medium",
    status: "in-progress",
    tags: ["Mobile", "Internationalization", "Localization"],
    assignee: "Carlos",
    createdAt: { date: "2025-12-09", time: "12:30" },
    updatedAt: { date: "2025-12-12", time: "17:00" },
  },
  {
    id: 29,
    title: "Task 29: Conduct User Interviews",
    description:
      "Schedule and run 10 user interviews to validate new search feature assumptions.",
    dueAt: { date: "2026-01-18", time: "16:00" },
    priority: "Medium",
    status: "todo",
    tags: ["Research", "UX", "Interviews"],
    assignee: "Maya",
    createdAt: { date: "2025-12-05", time: "11:00" },
    updatedAt: { date: "2025-12-05", time: "11:00" },
  },
  {
    id: 30,
    title: "Task 30: Upgrade Database Schema",
    description:
      "Plan and execute schema migration for adding multi-tenancy support with zero downtime.",
    dueAt: { date: "2026-01-30", time: "20:00" },
    priority: "High",
    status: "in-progress",
    tags: ["Database", "Backend", "Migration"],
    assignee: "Felix",
    createdAt: { date: "2025-12-06", time: "08:45" },
    updatedAt: { date: "2025-12-12", time: "19:15" },
  },
  {
    id: 31,
    title: "Task 31: Implement Rate Limiting",
    description:
      "Add robust API rate limiting with Redis to prevent abuse and DoS attacks.",
    dueAt: { date: "2026-01-08", time: "23:59" },
    priority: "High",
    status: "in-progress",
    tags: ["Security", "Backend", "Performance"],
    assignee: "Arjun",
    createdAt: { date: "2025-12-10", time: "09:15" },
    updatedAt: { date: "2025-12-12", time: "22:40" },
  },
  {
    id: 32,
    title: "Task 32: Create Annual Report Design",
    description:
      "Design visually appealing 2025 annual report for stakeholders and investors.",
    dueAt: { date: "2025-12-28", time: "18:00" },
    priority: "High",
    status: "todo",
    tags: ["Design", "Branding", "Corporate"],
    assignee: "Priya",
    createdAt: { date: "2025-12-09", time: "14:20" },
    updatedAt: { date: "2025-12-09", time: "14:20" },
  },
  {
    id: 33,
    title: "Task 33: Migrate Emails to New Provider",
    description:
      "Transition all company emails from GSuite to Microsoft 365 with zero downtime.",
    dueAt: { date: "2026-01-20", time: "20:00" },
    priority: "High",
    status: "review",
    tags: ["IT", "Migration", "Admin"],
    assignee: "Rahul",
    createdAt: { date: "2025-12-05", time: "11:00" },
    updatedAt: { date: "2025-12-12", time: "17:30" },
  },
  {
    id: 34,
    title: "Task 34: Add GraphQL Endpoint",
    description:
      "Expose a new GraphQL API alongside REST for flexible frontend queries.",
    dueAt: { date: "2026-02-05", time: "17:00" },
    priority: "Medium",
    status: "in-progress",
    tags: ["API", "Backend", "GraphQL"],
    assignee: "Vikram",
    createdAt: { date: "2025-12-11", time: "10:00" },
    updatedAt: { date: "2025-12-12", time: "19:10" },
  },
  {
    id: 35,
    title: "Task 35: Run Accessibility Audit",
    description:
      "Conduct full WCAG 2.2 AA audit and fix critical accessibility issues.",
    dueAt: { date: "2026-01-15", time: "23:59" },
    priority: "High",
    status: "todo",
    tags: ["A11y", "UX", "Compliance"],
    assignee: "Ananya",
    createdAt: { date: "2025-12-08", time: "13:30" },
    updatedAt: { date: "2025-12-08", time: "13:30" },
  },
  {
    id: 36,
    title: "Task 36: Automate Invoice Generation",
    description:
      "Build automated PDF invoice generator triggered on subscription renewal.",
    dueAt: { date: "2026-01-10", time: "15:00" },
    priority: "Medium",
    status: "done",
    tags: ["Automation", "Billing", "Backend"],
    assignee: "Kiran",
    createdAt: { date: "2025-12-03", time: "16:45" },
    updatedAt: { date: "2025-12-12", time: "10:20" },
  },
  {
    id: 37,
    title: "Task 37: Organize Tech Talk Series",
    description:
      "Plan and schedule internal tech talk series for Q1 2026 with external speakers.",
    dueAt: { date: "2025-12-30", time: "17:00" },
    priority: "Low",
    status: "in-progress",
    tags: ["Community", "Learning", "Events"],
    assignee: "Neha",
    createdAt: { date: "2025-12-06", time: "12:00" },
    updatedAt: { date: "2025-12-12", time: "14:15" },
  },
  {
    id: 38,
    title: "Task 38: Implement WebSockets Chat",
    description:
      "Add real-time chat functionality using Socket.io for customer support agents.",
    dueAt: { date: "2026-02-20", time: "20:00" },
    priority: "Medium",
    status: "todo",
    tags: ["Realtime", "Frontend", "Support"],
    assignee: "Amit",
    createdAt: { date: "2025-12-10", time: "15:30" },
    updatedAt: { date: "2025-12-10", time: "15:30" },
  },
  {
    id: 39,
    title: "Task 39: Archive Old Projects",
    description:
      "Clean up and archive all completed client projects older than 3 years from storage.",
    dueAt: { date: "2026-01-31", time: "18:00" },
    priority: "Low",
    status: "in-progress",
    tags: ["Maintenance", "Cleanup", "Storage"],
    assignee: "Sonia",
    createdAt: { date: "2025-12-07", time: "09:45" },
    updatedAt: { date: "2025-12-12", time: "11:00" },
  },
  {
    id: 40,
    title: "Task 40: Launch Referral Program",
    description:
      "Design and launch customer referral program with tracking and reward system.",
    dueAt: { date: "2025-12-25", time: "23:59" },
    priority: "High",
    status: "review",
    tags: ["Growth", "Marketing", "Product"],
    assignee: "Rohan",
    createdAt: { date: "2025-12-04", time: "10:30" },
    updatedAt: { date: "2025-12-12", time: "21:45" },
  },
];
